#!/usr/bin/bash

# i3
cp ~/.config/i3/config ~/fun/dotfiles/i3/i3config
# nvim
cp ~/.config/nvim/init.vim ~/fun/dotfiles/nvim/init.vim.bak
# shell
cp ~/.config/fish/config.fish ~/fun/dotfiles/shell/config.fish
cp ~/.profile ~/fun/dotfiles/shell/
# tmux
cp ~/.tmux.conf ~/fun/dotfiles/tmux/tmux.conf.bak

cd ~/fun/dotfiles

git add -A
git commit -m "Update Dots: Script Commit"
git push
